name:                xmonad-config
version:             0.1.0.0
author:              "leoniv"

dependencies:
- base >= 4.7 && < 5
- xmonad
- xmonad-contrib

executables:
  foo-exe:
    main:                xmonad-config.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
